### ISSUE TITLE
error loading weights

### ISSUE THREAD

**Issue by Reasat** [asiff00/Bangla-Llama#1]
Hi, thanks for the finetuned models!

Could you share your code for model loading and python env details?

The inference example posted in the readme is giving me a weights mismatch error.

```shell
Traceback (most recent call last):
  File "/home/reasat/Projects/Bangla-Llama/inference.py", line 4, in <module>
    pipe = pipeline("question-answering", model="asif00/bangla-llama", 
  File "/home/reasat/miniconda3/envs/phison/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 870, in pipeline
    framework, model = infer_framework_load_model(
  File "/home/reasat/miniconda3/envs/phison/lib/python3.10/site-packages/transformers/pipelines/base.py", line 269, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home/reasat/miniconda3/envs/phison/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3480, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/reasat/miniconda3/envs/phison/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3931, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
	size mismatch for model.layers.0.self_attn.q_proj.weight: copying a param with shape torch.Size([8388608, 1]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.0.self_attn.k_proj.weight: copying a param with shape torch.Size([2097152, 1]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
	size mismatch for model.layers.0.self_attn.v_proj.weight: copying a param with shape torch.Size([2097152, 1]) from checkpoint, the shape in current model is torch.Size([1024, 4096]).
	size mismatch for model.layers.0.self_attn.o_proj.weight: copying a param with shape torch.Size([8388608, 1]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for model.layers.0.mlp.gate_proj.weight: copying a param with shape torch.Size([29360128, 1]) from checkpoint, the shape in current model is torch.Size([14336, 4096]).
	size mismatch for model.layers.0.mlp.up_proj.weight: copying a param with shape torch.Size([29360128, 1]) from checkpoint, the shape in current model is torch.Size([14336, 4096]).
	size mismatch for model.layers.0.mlp.down_proj.weight: copying a param with shape torch.Size([29360128, 1]) from checkpoint, the shape in current model is torch.Size([4096, 14336]).
	size mismatch for model.layers.1.self_attn.q_proj.weight: copying a param with shape torch.Size([8388608, 1]) from checkpoint, the shape in current model is torch.
...
...
```

**Comment by asiff00** [comment]
@Reasat  Hello there!  There was an oversight, I have updated the README. 

# Installes
```shell
%pip install bitsandbytes==0.41.3 -q
%pip install transformers==4.40.1 -q
%pip install peft==0.11.1 -q
%pip install accelerate==0.31.0 -q
%pip install sentence_transformers==3.0.1 -q
```

### If you are using the pipeline

```Python
from transformers import pipeline
pipe = pipeline("text-generation", model="asif00/bangla-llama") 
```
or,

### Load model directly
```Python
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("asif00/bangla-llama")
model = AutoModelForCausalLM.from_pretrained("asif00/bangla-llama")
```

## I'll recomending using the following:

```python
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("asif00/bangla-llama")
model = AutoModelForCausalLM.from_pretrained("asif00/bangla-llama")

# General Prompt Structure: 

prompt = """Below is an instruction in Bengali language that describes a task, paired with an input also in Bengali language that provides further context. Write a response in Bengali language that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}
"""

# To get a cleaned-up version of the response, you can use the `generate_response` function:

def generate_response(question, context):
    inputs = tokenizer([prompt.format(question, context, "")], return_tensors="pt").to("cuda")
    outputs = model.generate(**inputs, max_new_tokens=1024, use_cache=True)
    responses = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
    response_start = responses.find("### Response:") + len("### Response:")
    response = responses[response_start:].strip()
    return response


# Example Usage:

question = "ভারতীয় বাঙালি কথাসাহিত্যিক মহাশ্বেতা দেবীর মৃত্যু কবে হয় ?"
context = "২০১৬ সালের ২৩ জুলাই হৃদরোগে আক্রান্ত হয়ে মহাশ্বেতা দেবী কলকাতার বেল ভিউ ক্লিনিকে ভর্তি হন। সেই বছরই ২৮ জুলাই একাধিক অঙ্গ বিকল হয়ে তাঁর মৃত্যু ঘটে। তিনি মধুমেহ, সেপ্টিসেমিয়া ও মূত্র সংক্রমণ রোগেও ভুগছিলেন।"
answer = generate_response(question, context)
print(answer)
```

**Comment by Reasat** [comment]
Thanks!
